// Auto-generated by nest-scramble v5.3.0 — do not edit manually
// Re-generate: npx nest-scramble generate src --format client

// ─── Enums ───────────────────────────────────────────────────────────
export type ProductStatus = 'draft' | 'active' | 'archived';

// ─── Types ───────────────────────────────────────────────────────────
export type ArrayBufferLike = unknown;
export interface BufferOfArrayBufferLike {
  /** The size in bytes of each element in the array. */
  BYTES_PER_ELEMENT: number;
  /** The ArrayBuffer instance referenced by the array. */
  buffer: ArrayBufferLike;
  /** The length in bytes of the array. */
  byteLength: number;
  /** The offset in bytes of the array. */
  byteOffset: number;
  /** The length of the array. */
  length: number;
  __@toStringTag@292: "Uint8Array";
}

export interface CreateProductDto {
  name: string;
  price: number;
  status: ProductStatus;
  category: ProductCategoryDto;
}

export interface CreateUserDto {
  name: string;
  email: string;
  age: number;
}

export interface Error {
  name: string;
  message: string;
  stack?: string;
}

export interface File {
  /** Name of the form field associated with this file. */
  fieldname: string;
  /** Name of the file on the uploader's computer. */
  originalname: string;
  /** Value of the `Content-Transfer-Encoding` header for this file. */
  encoding: string;
  /** Value of the `Content-Type` header for this file. */
  mimetype: string;
  /** Size of the file in bytes. */
  size: number;
  /** A readable stream of this file. Only available to the `_handleFile`
callback for custom `StorageEngine`s. */
  stream: Readable;
  /** `DiskStorage` only: Directory to which this file has been uploaded. */
  destination: string;
  /** `DiskStorage` only: Name of this file within `destination`. */
  filename: string;
  /** `DiskStorage` only: Full path to the uploaded file. */
  path: string;
  /** `MemoryStorage` only: A Buffer containing the entire file. */
  buffer: BufferOfArrayBufferLike;
}

export interface ProductCategoryDto {
  name: string;
  description?: string;
  id: number;
  createdAt: string;
}

export interface ProductResponseDto {
  name: string;
  price: number;
  status: ProductStatus;
  category: ProductCategoryDto;
  id: number;
  createdAt: string;
}

export interface Readable {
  /** Returns whether the stream was destroyed or errored before emitting `'end'`. */
  readableAborted: boolean;
  /** Is `true` if it is safe to call {@link read}, which means
the stream has not been destroyed or emitted `'error'` or `'end'`. */
  readable: boolean;
  /** Returns whether `'data'` has been emitted. */
  readableDidRead: boolean;
  /** Getter for the property `encoding` of a given `Readable` stream. The `encoding` property can be set using the {@link setEncoding} method. */
  readableEncoding: string;
  /** Becomes `true` when [`'end'`](https://nodejs.org/docs/latest-v20.x/api/stream.html#event-end) event is emitted. */
  readableEnded: boolean;
  /** This property reflects the current state of a `Readable` stream as described
in the [Three states](https://nodejs.org/docs/latest-v20.x/api/stream.html#three-states) section. */
  readableFlowing: boolean;
  /** Returns the value of `highWaterMark` passed when creating this `Readable`. */
  readableHighWaterMark: number;
  /** This property contains the number of bytes (or objects) in the queue
ready to be read. The value provides introspection data regarding
the status of the `highWaterMark`. */
  readableLength: number;
  /** Getter for the property `objectMode` of a given `Readable` stream. */
  readableObjectMode: boolean;
  /** Is `true` after `readable.destroy()` has been called. */
  destroyed: boolean;
  /** Is `true` after `'close'` has been emitted. */
  closed: boolean;
  /** Returns error if the stream has been destroyed with an error. */
  errored: Error;
}

export interface UpdateProductDto {
  name?: string;
  price?: number;
}

export interface UpdateUserDto {
  name?: string;
  email?: string;
}

export interface UserResponseDto {
  id: number;
  name: string;
  email: string;
  age: number;
}

export class UsersControllerClient {
  constructor(private readonly baseUrl: string) {}

  async findAll(name?: string): Promise<UserResponseDto[]> {
    const _url = new URL(`${this.baseUrl}/api/users`);
    if (name !== undefined) _url.searchParams.set('name', String(name));
    const _res = await fetch(_url.toString());
    if (!_res.ok) throw new Error(`findAll failed: ${_res.status}`);
    return _res.json() as Promise<UserResponseDto[]>;
  }

  async findOne(id: number): Promise<UserResponseDto> {
    const _res = await fetch(`${this.baseUrl}/api/users/${id}`);
    if (!_res.ok) throw new Error(`findOne failed: ${_res.status}`);
    return _res.json() as Promise<UserResponseDto>;
  }

  async create(createUserDto: CreateUserDto): Promise<UserResponseDto> {
    const _res = await fetch(`${this.baseUrl}/api/users`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(createUserDto),
    });
    if (!_res.ok) throw new Error(`create failed: ${_res.status}`);
    return _res.json() as Promise<UserResponseDto>;
  }

  async update(id: number, updateUserDto: UpdateUserDto): Promise<UserResponseDto> {
    const _res = await fetch(`${this.baseUrl}/api/users/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(updateUserDto),
    });
    if (!_res.ok) throw new Error(`update failed: ${_res.status}`);
    return _res.json() as Promise<UserResponseDto>;
  }

  async remove(id: number): Promise<{ deleted: boolean; }> {
    const _res = await fetch(`${this.baseUrl}/api/users/${id}`, { method: 'DELETE' });
    if (!_res.ok) throw new Error(`remove failed: ${_res.status}`);
    return _res.json() as Promise<{ deleted: boolean; }>;
  }

}

export class ProductsControllerClient {
  constructor(private readonly baseUrl: string) {}

  async findAll(status?: ProductStatus): Promise<ProductResponseDto[]> {
    const _url = new URL(`${this.baseUrl}/api/products`);
    if (status !== undefined) _url.searchParams.set('status', String(status));
    const _res = await fetch(_url.toString());
    if (!_res.ok) throw new Error(`findAll failed: ${_res.status}`);
    return _res.json() as Promise<ProductResponseDto[]>;
  }

  async findOne(id: number): Promise<ProductResponseDto> {
    const _res = await fetch(`${this.baseUrl}/api/products/${id}`);
    if (!_res.ok) throw new Error(`findOne failed: ${_res.status}`);
    return _res.json() as Promise<ProductResponseDto>;
  }

  async create(createProductDto: CreateProductDto): Promise<ProductResponseDto> {
    const _res = await fetch(`${this.baseUrl}/api/products`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(createProductDto),
    });
    if (!_res.ok) throw new Error(`create failed: ${_res.status}`);
    return _res.json() as Promise<ProductResponseDto>;
  }

  async update(id: number, updateProductDto: UpdateProductDto): Promise<ProductResponseDto> {
    const _res = await fetch(`${this.baseUrl}/api/products/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(updateProductDto),
    });
    if (!_res.ok) throw new Error(`update failed: ${_res.status}`);
    return _res.json() as Promise<ProductResponseDto>;
  }

  async remove(id: number): Promise<{ deleted: boolean; }> {
    const _res = await fetch(`${this.baseUrl}/api/products/${id}`, { method: 'DELETE' });
    if (!_res.ok) throw new Error(`remove failed: ${_res.status}`);
    return _res.json() as Promise<{ deleted: boolean; }>;
  }

  async uploadImage(file: File): Promise<{ filename: string; }> {
    const _form = new FormData();
    _form.append('file', file);
    const _res = await fetch(`${this.baseUrl}/api/products/upload`, {
      method: 'POST',
      body: _form,
    });
    if (!_res.ok) throw new Error(`uploadImage failed: ${_res.status}`);
    return _res.json() as Promise<{ filename: string; }>;
  }

}

// ─── Aggregate client ───────────────────────────────────────────────────────
export class ApiClient {
  readonly users: UsersControllerClient;
  readonly products: ProductsControllerClient;

  constructor(baseUrl: string) {
    this.users = new UsersControllerClient(baseUrl);
    this.products = new ProductsControllerClient(baseUrl);
  }
}